export const FETCH_PLANETS_REQUEST = 'FETCH_PLANETS_REQUEST';
export const FETCH_PLANETS_SUCCESS = 'FETCH_PLANETS_SUCCESS';
export const FETCH_PLANETS_FAILURE = 'FETCH_PLANETS_FAILURE';

export const FETCH_VEHICLES_REQUEST = 'FETCH_VEHICLES_REQUEST';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_FAILURE = 'FETCH_VEHICLES_FAILURE';

export const SET_SELECTED_PLANET = 'SET_SELECTED_PLANET';
export const SET_SELECTED_VEHICLE = 'SET_SELECTED_VEHICLE';
